[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM6
monitor_port = COM6
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[platformio]
src_dir = firmware/core/src
include_dir = firmware/core/include
lib_dir = firmware/core/lib
test_dir = firmware/core/test